#!/bin/sh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

# force une version de Node
nvm use default >/dev/null 2>&1 || nvm use 20 >/dev/null 2>&1

node -v || exit 1
npm -v || exit 1
pnpm -v || exit 1

pnpm lint-staged
